-- MySQL Script generated by MySQL Workbench
-- Tue Jul 13 17:55:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Pizzeria` ;

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`Provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Provincias` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Provincias` (
  `Provincias_id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Provincias_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Localidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Localidades` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Localidades` (
  `Localidades_id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Provincia` INT NOT NULL,
  PRIMARY KEY (`Localidades_id`),
  INDEX `fk_Localidad_Provincia1_idx` (`Provincia` ASC) VISIBLE,
  CONSTRAINT `fk_Localidad_Provincia1`
    FOREIGN KEY (`Provincia`)
    REFERENCES `Pizzeria`.`Provincias` (`Provincias_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Clientes` (
  `Clientes_id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(15) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NULL,
  `CP` VARCHAR(5) NOT NULL,
  `Localidad` INT NOT NULL,
  `Provincia` INT NOT NULL,
  `Telefono` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`Clientes_id`),
  INDEX `fk_Clientes_Localidad1_idx` (`Localidad` ASC, `Provincia` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Localidad1`
    FOREIGN KEY (`Localidad` , `Provincia`)
    REFERENCES `Pizzeria`.`Localidades` (`Localidades_id` , `Provincia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Tiendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Tiendas` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Tiendas` (
  `Tiendas_id` INT NOT NULL AUTO_INCREMENT,
  `Direccion` VARCHAR(45) NOT NULL,
  `CP` VARCHAR(5) NOT NULL,
  `Localidad` INT NOT NULL,
  `Provincia` INT NOT NULL,
  PRIMARY KEY (`Tiendas_id`),
  INDEX `fk_Tiendas_Localidades1_idx` (`Localidad` ASC, `Provincia` ASC) VISIBLE,
  CONSTRAINT `fk_Tiendas_Localidades1`
    FOREIGN KEY (`Localidad` , `Provincia`)
    REFERENCES `Pizzeria`.`Localidades` (`Localidades_id` , `Provincia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Empleados` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Empleados` (
  `Empleados_id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `NIF` VARCHAR(10) NOT NULL,
  `Teléfono` VARCHAR(11) NOT NULL,
  `Categoría` ENUM('Cocinero', 'Repartidor') NOT NULL COMMENT 'El empleado puede ser:\nCocinero\nRepartidor',
  `Tienda` INT NOT NULL COMMENT 'Tienda en la que trabaja el empleado',
  PRIMARY KEY (`Empleados_id`),
  UNIQUE INDEX `DNI_UNIQUE` (`NIF` ASC) VISIBLE,
  INDEX `fk_Empleados_Tiendas1_idx` (`Tienda` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_Tiendas1`
    FOREIGN KEY (`Tienda`)
    REFERENCES `Pizzeria`.`Tiendas` (`Tiendas_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Repartos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Repartos` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Repartos` (
  `Repartos_id` INT NOT NULL AUTO_INCREMENT,
  `Pedido` INT NOT NULL COMMENT 'Número del pedido a domicilio',
  `Repartidor` INT NOT NULL COMMENT 'Empleado que entrega el pedido',
  `FechaHora_Entrega` DATETIME NOT NULL,
  PRIMARY KEY (`Repartos_id`),
  INDEX `fk_Repartos_Empleados1_idx` (`Repartidor` ASC) VISIBLE,
  INDEX `fk_Repartos_Pedidos1_idx` (`Pedido` ASC) VISIBLE,
  UNIQUE INDEX `Pedido_UNIQUE` (`Pedido` ASC) VISIBLE,
  CONSTRAINT `fk_Repartos_Empleados1`
    FOREIGN KEY (`Repartidor`)
    REFERENCES `Pizzeria`.`Empleados` (`Empleados_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Repartos_Pedidos1`
    FOREIGN KEY (`Pedido`)
    REFERENCES `Pizzeria`.`Pedidos` (`Pedidos_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Pedidos` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pedidos` (
  `Pedidos_id` INT NOT NULL AUTO_INCREMENT,
  `Cliente` INT NOT NULL,
  `Tienda` INT NOT NULL,
  `FechaHora` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Tipo` ENUM('Domicilio', 'Tienda') NOT NULL COMMENT 'Tipo de entrega del pedido:\nDomicilio = se reparte en el domicilio cliente\nTienda = el cliente lo recoge en la tienda',
  `Reparto` INT NULL,
  PRIMARY KEY (`Pedidos_id`),
  INDEX `fk_Pedidos_Clientes1_idx` (`Cliente` ASC) VISIBLE,
  INDEX `fk_Pedidos_Tiendas1_idx` (`Tienda` ASC) VISIBLE,
  INDEX `fk_Pedidos_Repartos1_idx` (`Reparto` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente`
    FOREIGN KEY (`Cliente`)
    REFERENCES `Pizzeria`.`Clientes` (`Clientes_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Tienda`
    FOREIGN KEY (`Tienda`)
    REFERENCES `Pizzeria`.`Tiendas` (`Tiendas_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Reparto`
    FOREIGN KEY (`Reparto`)
    REFERENCES `Pizzeria`.`Repartos` (`Repartos_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Pedidos_has_Hamburguesas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Pedidos_has_Hamburguesas` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pedidos_has_Hamburguesas` (
  `Pedidos_Pedidos_id` INT NOT NULL,
  `Pedidos_Cliente` INT NOT NULL,
  `Pedidos_Tienda` INT NOT NULL,
  `Hamburguesas_Hamburguesas_id` INT NOT NULL,
  PRIMARY KEY (`Pedidos_Pedidos_id`, `Pedidos_Cliente`, `Pedidos_Tienda`, `Hamburguesas_Hamburguesas_id`),
  INDEX `fk_Pedidos_has_Hamburguesas_Pedidos1_idx` (`Pedidos_Pedidos_id` ASC, `Pedidos_Cliente` ASC, `Pedidos_Tienda` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_has_Hamburguesas_Pedidos1`
    FOREIGN KEY (`Pedidos_Pedidos_id` , `Pedidos_Cliente` , `Pedidos_Tienda`)
    REFERENCES `Pizzeria`.`Pedidos` (`Pedidos_id` , `Cliente` , `Tienda`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Pedidos_has_Pizzas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Pedidos_has_Pizzas` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pedidos_has_Pizzas` (
  `Pedidos_Pedidos_id` INT NOT NULL,
  `Pedidos_Cliente` INT NOT NULL,
  `Pedidos_Tienda` INT NOT NULL,
  `Pizzas_Pizzas_id` INT NOT NULL,
  `Pizzas_Categoria` INT NOT NULL,
  PRIMARY KEY (`Pedidos_Pedidos_id`, `Pedidos_Cliente`, `Pedidos_Tienda`, `Pizzas_Pizzas_id`, `Pizzas_Categoria`),
  INDEX `fk_Pedidos_has_Pizzas_Pedidos1_idx` (`Pedidos_Pedidos_id` ASC, `Pedidos_Cliente` ASC, `Pedidos_Tienda` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_has_Pizzas_Pedidos1`
    FOREIGN KEY (`Pedidos_Pedidos_id` , `Pedidos_Cliente` , `Pedidos_Tienda`)
    REFERENCES `Pizzeria`.`Pedidos` (`Pedidos_id` , `Cliente` , `Tienda`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`TipoProductos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`TipoProductos` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`TipoProductos` (
  `TipoProductos_id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TipoProductos_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`PizzasCategorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`PizzasCategorias` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`PizzasCategorias` (
  `PizzasCategorias_id` INT NOT NULL AUTO_INCREMENT,
  `NombreCategoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PizzasCategorias_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`Productos` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`Productos` (
  `Productos_id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(15) NOT NULL,
  `Descripcion` VARCHAR(255) NULL,
  `Imagen` TINYBLOB NULL,
  `Precio` DECIMAL NOT NULL,
  `TipoProductos_TipoProductos_id` INT NOT NULL,
  `PizzasCategorias_PizzasCategorias_id` INT NULL,
  PRIMARY KEY (`Productos_id`),
  INDEX `fk_Productos_TipoProductos1_idx` (`TipoProductos_TipoProductos_id` ASC) VISIBLE,
  INDEX `fk_Productos_PizzasCategorias1_idx` (`PizzasCategorias_PizzasCategorias_id` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_TipoProductos1`
    FOREIGN KEY (`TipoProductos_TipoProductos_id`)
    REFERENCES `Pizzeria`.`TipoProductos` (`TipoProductos_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Productos_PizzasCategorias1`
    FOREIGN KEY (`PizzasCategorias_PizzasCategorias_id`)
    REFERENCES `Pizzeria`.`PizzasCategorias` (`PizzasCategorias_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`ProductosPedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`ProductosPedido` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`ProductosPedido` (
  `ProductosPedido_id` INT NOT NULL AUTO_INCREMENT,
  `Pedidos_Pedidos_id` INT NOT NULL,
  `Productos_Productos_id` INT NOT NULL,
  `Cantidad` TINYINT NULL DEFAULT 0,
  INDEX `fk_Pedidos_has_Productos_Productos1_idx` (`Productos_Productos_id` ASC) VISIBLE,
  INDEX `fk_Pedidos_has_Productos_Pedidos1_idx` (`Pedidos_Pedidos_id` ASC) VISIBLE,
  PRIMARY KEY (`ProductosPedido_id`),
  CONSTRAINT `fk_Pedidos_has_Productos_Pedidos1`
    FOREIGN KEY (`Pedidos_Pedidos_id`)
    REFERENCES `Pizzeria`.`Pedidos` (`Pedidos_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pedidos_has_Productos_Productos1`
    FOREIGN KEY (`Productos_Productos_id`)
    REFERENCES `Pizzeria`.`Productos` (`Productos_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
