-- MySQL Script generated by MySQL Workbench
-- Sun Jul 18 17:57:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Spotify
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Spotify` ;

-- -----------------------------------------------------
-- Schema Spotify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Spotify` DEFAULT CHARACTER SET utf8 ;
USE `Spotify` ;

-- -----------------------------------------------------
-- Table `Spotify`.`FormasPagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotify`.`FormasPagos` ;

CREATE TABLE IF NOT EXISTS `Spotify`.`FormasPagos` (
  `Id_FormaPago` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Id_FormaPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotify`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `Spotify`.`Usuarios` (
  `Id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(15) NOT NULL,
  `fechaNac` DATETIME NOT NULL,
  `pais` VARCHAR(15) NOT NULL,
  `CP` VARCHAR(5) NOT NULL,
  `Tipo_usuario` ENUM('free', 'premium') NOT NULL,
  `Id_FormaPago` INT NULL,
  PRIMARY KEY (`Id_Usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_Usuarios_FormasPagos1_idx` (`Id_FormaPago` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_FormasPagos1`
    FOREIGN KEY (`Id_FormaPago`)
    REFERENCES `Spotify`.`FormasPagos` (`Id_FormaPago`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Playlists_Estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotify`.`Playlists_Estados` ;

CREATE TABLE IF NOT EXISTS `Spotify`.`Playlists_Estados` (
  `Id_Estado` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Playlists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotify`.`Playlists` ;

CREATE TABLE IF NOT EXISTS `Spotify`.`Playlists` (
  `Id_Playlist` INT NOT NULL AUTO_INCREMENT,
  `Num_canciones` TINYINT NOT NULL,
  `Fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Id_Propietario` INT NOT NULL COMMENT 'Usuario que crea la playlist',
  `Playlists_Estados_Id_Estado` INT NOT NULL,
  PRIMARY KEY (`Id_Playlist`, `Playlists_Estados_Id_Estado`),
  INDEX `fk_Playlists_Usuarios1_idx` (`Id_Propietario` ASC) VISIBLE,
  INDEX `fk_Playlists_Playlists_Estados1_idx` (`Playlists_Estados_Id_Estado` ASC) VISIBLE,
  CONSTRAINT `fk_Playlists_Usuarios1`
    FOREIGN KEY (`Id_Propietario`)
    REFERENCES `Spotify`.`Usuarios` (`Id_Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Playlists_Playlists_Estados1`
    FOREIGN KEY (`Playlists_Estados_Id_Estado`)
    REFERENCES `Spotify`.`Playlists_Estados` (`Id_Estado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Subscripciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotify`.`Subscripciones` ;

CREATE TABLE IF NOT EXISTS `Spotify`.`Subscripciones` (
  `id_Subscripcion` INT NOT NULL AUTO_INCREMENT,
  `Inicio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Renovacion` DATETIME NOT NULL,
  `Id_Usuario` INT NOT NULL,
  `Id_FormaPago` INT NOT NULL,
  PRIMARY KEY (`id_Subscripcion`),
  INDEX `fk_Subscripciones_Usuarios1_idx` (`Id_Usuario` ASC) VISIBLE,
  INDEX `fk_Subscripciones_FormasPagos1_idx` (`Id_FormaPago` ASC) VISIBLE,
  CONSTRAINT `fk_Subscripciones_Usuarios1`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `Spotify`.`Usuarios` (`Id_Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Subscripciones_FormasPagos1`
    FOREIGN KEY (`Id_FormaPago`)
    REFERENCES `Spotify`.`FormasPagos` (`Id_FormaPago`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Tarjetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotify`.`Tarjetas` ;

CREATE TABLE IF NOT EXISTS `Spotify`.`Tarjetas` (
  `Id_Tarjeta` INT NOT NULL AUTO_INCREMENT,
  `Num_tarjeta` INT(20) NOT NULL,
  `Mes_caduc` TINYINT(2) NOT NULL,
  `Año_caduc` TINYINT(4) NOT NULL,
  `Codigo_seguridad` TINYINT(3) NOT NULL,
  `Id_FormaPago` INT NOT NULL,
  PRIMARY KEY (`Id_Tarjeta`),
  UNIQUE INDEX `Num_tarjeta_UNIQUE` (`Num_tarjeta` ASC) VISIBLE,
  INDEX `fk_Tarjetas_FormasPagos_idx` (`Id_FormaPago` ASC) VISIBLE,
  CONSTRAINT `fk_Tarjetas_FormasPagos`
    FOREIGN KEY (`Id_FormaPago`)
    REFERENCES `Spotify`.`FormasPagos` (`Id_FormaPago`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`PayPal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotify`.`PayPal` ;

CREATE TABLE IF NOT EXISTS `Spotify`.`PayPal` (
  `id_Paypal` INT NOT NULL,
  `Nombre_usuarioPaypal` VARCHAR(45) NOT NULL,
  `Id_FormaPago` INT NOT NULL,
  PRIMARY KEY (`id_Paypal`),
  UNIQUE INDEX `Nombre_usuarioPaypal_UNIQUE` (`Nombre_usuarioPaypal` ASC) VISIBLE,
  INDEX `fk_PayPal_FormasPagos1_idx` (`Id_FormaPago` ASC) VISIBLE,
  CONSTRAINT `fk_PayPal_FormasPagos1`
    FOREIGN KEY (`Id_FormaPago`)
    REFERENCES `Spotify`.`FormasPagos` (`Id_FormaPago`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Pagos_Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotify`.`Pagos_Pedidos` ;

CREATE TABLE IF NOT EXISTS `Spotify`.`Pagos_Pedidos` (
  `Id_Pedido` INT NOT NULL,
  `id_Subscripcion` INT NOT NULL,
  `Usuarios_Id_FormaPago` INT NOT NULL,
  `Fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Precio` DECIMAL NOT NULL,
  PRIMARY KEY (`Id_Pedido`),
  INDEX `fk_Pedidos_Subscripciones1_idx` (`id_Subscripcion` ASC) VISIBLE,
  INDEX `fk_Pedidos_Usuarios1_idx` (`Usuarios_Id_FormaPago` ASC, `id_Subscripcion` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Subscripciones1`
    FOREIGN KEY (`id_Subscripcion`)
    REFERENCES `Spotify`.`Subscripciones` (`id_Subscripcion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pedidos_Usuarios1`
    FOREIGN KEY (`Usuarios_Id_FormaPago` , `id_Subscripcion`)
    REFERENCES `Spotify`.`Usuarios` (`Id_FormaPago` , `Id_FormaPago`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Artistas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotify`.`Artistas` ;

CREATE TABLE IF NOT EXISTS `Spotify`.`Artistas` (
  `Id_Artista` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Foto` BLOB NOT NULL,
  PRIMARY KEY (`Id_Artista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Albums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotify`.`Albums` ;

CREATE TABLE IF NOT EXISTS `Spotify`.`Albums` (
  `Id_Album` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Año publicacion` YEAR NOT NULL,
  `Portada` BLOB NOT NULL,
  `Id_Artista` INT NOT NULL,
  PRIMARY KEY (`Id_Album`, `Id_Artista`),
  INDEX `fk_Albums_Artistas1_idx` (`Id_Artista` ASC) VISIBLE,
  CONSTRAINT `fk_Albums_Artistas1`
    FOREIGN KEY (`Id_Artista`)
    REFERENCES `Spotify`.`Artistas` (`Id_Artista`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Canciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotify`.`Canciones` ;

CREATE TABLE IF NOT EXISTS `Spotify`.`Canciones` (
  `Id_Cancion` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Duracion` TINYINT NOT NULL COMMENT 'Duracion en segundos',
  `Num_reproducciones` INT NOT NULL,
  `Id_Album` INT NOT NULL,
  PRIMARY KEY (`Id_Cancion`, `Id_Album`),
  INDEX `fk_Canciones_Albums1_idx` (`Id_Album` ASC) VISIBLE,
  CONSTRAINT `fk_Canciones_Albums1`
    FOREIGN KEY (`Id_Album`)
    REFERENCES `Spotify`.`Albums` (`Id_Album`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Playlists_has_Canciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotify`.`Playlists_has_Canciones` ;

CREATE TABLE IF NOT EXISTS `Spotify`.`Playlists_has_Canciones` (
  `Playlists_Id_Playlist` INT NOT NULL,
  `Canciones_Id_Cancion` INT NOT NULL,
  `Fecha_inclusion` DATETIME NOT NULL,
  `Id_Usuario` INT NOT NULL COMMENT 'Usuario que añade la cancion',
  PRIMARY KEY (`Playlists_Id_Playlist`, `Canciones_Id_Cancion`),
  INDEX `fk_Playlists_has_Canciones_Canciones1_idx` (`Canciones_Id_Cancion` ASC) VISIBLE,
  INDEX `fk_Playlists_has_Canciones_Playlists1_idx` (`Playlists_Id_Playlist` ASC) VISIBLE,
  INDEX `fk_Playlists_has_Canciones_Usuarios1_idx` (`Id_Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Playlists_has_Canciones_Playlists1`
    FOREIGN KEY (`Playlists_Id_Playlist`)
    REFERENCES `Spotify`.`Playlists` (`Id_Playlist`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Playlists_has_Canciones_Canciones1`
    FOREIGN KEY (`Canciones_Id_Cancion`)
    REFERENCES `Spotify`.`Canciones` (`Id_Cancion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Playlists_has_Canciones_Usuarios1`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `Spotify`.`Usuarios` (`Id_Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Usuarios_has_Artistas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotify`.`Usuarios_has_Artistas` ;

CREATE TABLE IF NOT EXISTS `Spotify`.`Usuarios_has_Artistas` (
  `Usuarios_Id_Usuario` INT NOT NULL,
  `Artistas_Id_Artista` INT NOT NULL,
  PRIMARY KEY (`Usuarios_Id_Usuario`, `Artistas_Id_Artista`),
  INDEX `fk_Usuarios_has_Artistas_Artistas1_idx` (`Artistas_Id_Artista` ASC) VISIBLE,
  INDEX `fk_Usuarios_has_Artistas_Usuarios1_idx` (`Usuarios_Id_Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_has_Artistas_Usuarios1`
    FOREIGN KEY (`Usuarios_Id_Usuario`)
    REFERENCES `Spotify`.`Usuarios` (`Id_Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Usuarios_has_Artistas_Artistas1`
    FOREIGN KEY (`Artistas_Id_Artista`)
    REFERENCES `Spotify`.`Artistas` (`Id_Artista`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Artistas_Relacionados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotify`.`Artistas_Relacionados` ;

CREATE TABLE IF NOT EXISTS `Spotify`.`Artistas_Relacionados` (
  `Id_Artista` INT NOT NULL,
  `Artista_Relacionado` INT NOT NULL,
  PRIMARY KEY (`Id_Artista`, `Artista_Relacionado`),
  INDEX `fk_Artistas_has_Artistas_Artistas2_idx` (`Artista_Relacionado` ASC) VISIBLE,
  INDEX `fk_Artistas_has_Artistas_Artistas1_idx` (`Id_Artista` ASC) VISIBLE,
  CONSTRAINT `fk_Artistas_has_Artistas_Artistas1`
    FOREIGN KEY (`Id_Artista`)
    REFERENCES `Spotify`.`Artistas` (`Id_Artista`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Artistas_has_Artistas_Artistas2`
    FOREIGN KEY (`Artista_Relacionado`)
    REFERENCES `Spotify`.`Artistas` (`Id_Artista`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`Canciones _Favoritas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Spotify`.`Canciones _Favoritas` ;

CREATE TABLE IF NOT EXISTS `Spotify`.`Canciones _Favoritas` (
  `Id_Favoritos` INT NOT NULL AUTO_INCREMENT,
  `Id_Usuario` INT NOT NULL,
  `Id_Cancion` INT NOT NULL,
  `Id_Album` INT NOT NULL,
  INDEX `fk_Usuarios_has_Canciones_Canciones1_idx` (`Id_Cancion` ASC, `Id_Album` ASC) VISIBLE,
  INDEX `fk_Usuarios_has_Canciones_Usuarios1_idx` (`Id_Usuario` ASC) VISIBLE,
  PRIMARY KEY (`Id_Favoritos`),
  CONSTRAINT `fk_Usuarios_has_Canciones_Usuarios1`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `Spotify`.`Usuarios` (`Id_Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Usuarios_has_Canciones_Canciones1`
    FOREIGN KEY (`Id_Cancion` , `Id_Album`)
    REFERENCES `Spotify`.`Canciones` (`Id_Cancion` , `Id_Album`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
